include: package:flutter_lints/flutter.yaml
linter:
  rules:
    prefer_single_quotes: true
    directives_ordering: true
    unnecessary_final: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
