default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play Internal Track"
  lane :deploy_internal_track do

    upload_to_play_store(
      json_key_data: ENV['GOOGLE_PLAY_JSON'],
      package_name: "com.zorgbijjou.patientapp",
      aab: ENV['AAB_PATH'],
      track: "internal",
      release_status: "draft", #TODO: Remove this line when Play Console is ready
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      mapping_paths: [ENV['SYMBOL_PATH'], ENV['MAPPING_PATH']]
    )
  end
end
