name: onboarding
description: "Onboarding Module"
version: 0.0.1

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  core: ^0.0.0
  theme: ^0.0.0
  equatable: ^2.0.7
  mocktail: ^1.0.4
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  mask_text_input_formatter: ^2.9.0
  flutter_riverpod: ^2.5.1

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: 5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  assets:
    - assets/images/