name: zorg_bij_jou
description: "Zorg bij jou app - Supports the patient journey through Hybrid Care."
publish_to: "none"
version: 0.1.36+42

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  core: ^0.0.0
  theme: ^0.0.0
  faq: ^0.0.0
  onboarding: ^0.0.0
  chat: ^0.0.0
  go_router: ^14.2.1
  flutter_riverpod: ^2.5.1
  uuid: ^4.5.0
  shared_preferences: ^2.3.3
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.11
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.1
  flutter_lints: 5.0.0
  flutter_native_splash: ^2.4.1
  path: ^1.9.0
  fake_async: ^1.3.1

  intl: any
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/faq/
    - assets/onboarding/
    - packages/core/l10n/core_nl.arb
    - packages/core/l10n/core_en.arb

flutter_launcher_icons:
  android: true
  adaptive_icon_background: assets/icon/icon_background.png
  adaptive_icon_foreground: assets/icon/icon_foreground_adaptive.png
  adaptive_icon_monochrome: assets/icon/icon_foreground_adaptive.png
  adaptive_icon_foreground_inset: 23
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#057982"
  image_path: assets/icon/icon_foreground.png
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    background_color: "#057982"

flutter_native_splash:
  color: "#057982"
  image: assets/icon/icon_foreground.png
