name: widgetbook_workspace
description: "Widgetbook workspace for widget development and testing."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  theme: ^0.0.0
  core: ^0.0.0
  faq: ^0.0.0
  onboarding: ^0.0.0
  zorg_bij_jou: ^0.0.0
  chat: ^0.0.0
  widgetbook: ^3.8.1
  widgetbook_annotation: ^3.1.0
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  widgetbook_generator: ^3.8.0
  build_runner: ^2.4.11
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - packages/core/l10n/core_nl.arb
    - packages/core/l10n/core_en.arb
