default_platform(:ios)

platform :ios do
  before_all do
    setup_ci
  end

  desc "Build and sign the iOS app"
  lane :build_ipa do
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY_CONTENT']
    )

    sync_code_signing(
      api_key: api_key,
      type: "appstore",
      readonly: true,
    )

    build_ios_app(
      output_directory: "./build/ios/ipa",
      skip_build_archive: true,
      archive_path: "../build/ios/archive/Runner.xcarchive",
      export_team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      export_options: {
        provisioningProfiles: {
          "com.zorgbijjou.patientapp" => "match AppStore com.zorgbijjou.patientapp"
        }
      }
    )
  end

  desc "Release a new version to the App Store"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY_CONTENT']
    )

    upload_to_testflight(
      api_key: api_key, 
      ipa: "./build/ios/ipa/Runner.ipa",
      distribute_external: true,
      changelog: "New version",
      groups: [
        "Patienten Team"
      ],
    )
  end
end